seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: /glade/derecho/scratch/kvirji/s2s-forecasting/exps/aurora/0.25-pretrained/temporal_attention/phase1-6h-5.625_1step_14d_hist

  precision: 32

  devices: 4
  num_nodes: 1
  accelerator: gpu
  strategy:     
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      timeout: 02:00:00
      # find_unused_parameters: true
  
  min_epochs: 1
  max_epochs: 100
  enable_progress_bar: true

  sync_batchnorm: true
  enable_checkpointing: true

  # debugging
  fast_dev_run: false

  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ${trainer.default_root_dir}/logs
      name: null
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ""

  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
    
    - class_path: s2s.utils.callbacks.GradientMonitor
      init_args:
        log_every_n_steps: 50

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/checkpoints"
        monitor: "val/var_w_mae" # name of the logged metric which determines when model is improving
        mode: "min" # "max" means higher metric value is better, can be also "min"
        save_top_k: 1 # save k best models (determined by above metric)
        save_last: true # additionaly always save model from last epoch
        verbose: false
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: false

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "val/var_w_mae" # name of the logged metric which determines when model is improving
        mode: "min" # "max" means higher metric value is better, can be also "min"
        patience: 5 # how many validation epochs of not improving until training stops
        min_delta: 0. # minimum change in the monitored metric needed to qualify as an improvement

    - class_path: pytorch_lightning.callbacks.RichModelSummary
      init_args:
        max_depth: -1

    - class_path: pytorch_lightning.callbacks.RichProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  pretrained_path: /glade/derecho/scratch/kvirji/s2s-forecasting/pretrained_weights/aurora-0.25-pretrained.ckpt
  version: 0
  temporal_attention: true
  load_strict: false
  use_default_statistics: true
  delta_time: 6
  history_size: 56
  use_activation_checkpointing: true
  use_automatic_optimization: false
  training_phase: 1
  drop_path: 0.0
  drop_rate: 0.0
  use_lora: false
  lora_steps: 40
  lora_mode: single
  autocast: true
  optim_lr: 5e-5
  optim_beta_1: 0.9
  optim_beta_2: 0.999
  optim_weight_decay: 5e-6
  optim_warmup_steps: 2000
  optim_max_steps: 100000
  optim_warmup_start_lr: 0.0
  mae_alpha: 0.25
  mae_beta: 1.0
  mae_gamma: 1.0
  monitor_val_step: 1
  monitor_test_steps: [1,4,8,12,16,20,24,28,32,36,40]
  replay_buffer_lead_time_thresholds: [[4000, 24], [34000, 96], [105000, 168]]
  max_replay_buffer_size: 100
  send_replay_buffer_to_cpu: false


# ---------------------------- DATA -------------------------------------------
data:
  root_dir: /glade/derecho/scratch/kvirji/DATA/preprocessed/era5/1959-2023_01_10-6h-64x32_equiangular_conservative_n_shards_1
  climatology_val: /glade/derecho/scratch/kvirji/DATA/preprocessed/era5_climatology/1990-2019_6h_64x32_equiangular_conservative.zarr
  climatology_test: /glade/derecho/scratch/kvirji/DATA/preprocessed/era5_climatology/1990-2019_6h_64x32_equiangular_conservative.zarr
  # root_dir: /glade/derecho/scratch/kvirji/DATA/preprocessed/era5/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables_n_shards_8
  # climatology_val: /glade/derecho/scratch/kvirji/DATA/preprocessed/era5_climatology/1990-2017_6h_1440x721.zarr
  # climatology_test: /glade/derecho/scratch/kvirji/DATA/preprocessed/era5_climatology/1990-2019_6h_1440x721.zarr
  static_variables: [
    "land_sea_mask",
    "geopotential_at_surface",
    "soil_type",
    ]
  in_variables: [
      "2m_temperature",
      "10m_u_component_of_wind",
      "10m_v_component_of_wind",
      "mean_sea_level_pressure",
      "geopotential_50",
      "geopotential_100",
      "geopotential_150",
      "geopotential_200",
      "geopotential_250",
      "geopotential_300",      
      "geopotential_400",
      "geopotential_500",
      "geopotential_600",
      "geopotential_700",
      "geopotential_850",
      "geopotential_925",
      "geopotential_1000",
      "u_component_of_wind_50",
      "u_component_of_wind_100",
      "u_component_of_wind_150",
      "u_component_of_wind_200",
      "u_component_of_wind_250",
      "u_component_of_wind_300",
      "u_component_of_wind_400",
      "u_component_of_wind_500",
      "u_component_of_wind_600",
      "u_component_of_wind_700",
      "u_component_of_wind_850",
      "u_component_of_wind_925",
      "u_component_of_wind_1000",
      "v_component_of_wind_50",
      "v_component_of_wind_100",
      "v_component_of_wind_150",
      "v_component_of_wind_200",
      "v_component_of_wind_250",
      "v_component_of_wind_300",
      "v_component_of_wind_400",
      "v_component_of_wind_500",
      "v_component_of_wind_600",
      "v_component_of_wind_700",
      "v_component_of_wind_850",
      "v_component_of_wind_925",
      "v_component_of_wind_1000",
      "temperature_50",
      "temperature_100",
      "temperature_150",
      "temperature_200",
      "temperature_250",
      "temperature_300",
      "temperature_400",
      "temperature_500",
      "temperature_600",
      "temperature_700",
      "temperature_850",
      "temperature_925",
      "temperature_1000",
      "specific_humidity_50",
      "specific_humidity_100",
      "specific_humidity_150",
      "specific_humidity_200",
      "specific_humidity_250",
      "specific_humidity_300",
      "specific_humidity_400",
      "specific_humidity_500",
      "specific_humidity_600",
      "specific_humidity_700",
      "specific_humidity_850",
      "specific_humidity_925",
      "specific_humidity_1000",
    ]
  plot_variables: [
      "2m_temperature",
      "geopotential_500",
      "temperature_850",
  ]
  # [history_step * hrs_each_step * h = history timestamp (hrs)] for h in history_size 
  # [predict_step * hrs_each_step * lt = max lead time (hrs)] for lt in predict_size
  predict_size: 1
  predict_step: 1
  history_size: 55
  history_step: 1
  hrs_each_step: 6
  max_buffer_size: 100
  batch_size: 1
  mem_load: 1.0
  num_workers: 2
  pin_memory: true
  normalize_data: true